### 1.	Create a program that asks the user to enter their name and their age. Print out a message that tells them the year that they will turn 100 years old

In [ ]:
from datetime import datetime

In [5]:
def hundread_cal(name,age):
    hundred = int((100-age) + datetime.now().year)
    print('hello ',name, 'now u r in ',age,'You will turn 100 years old in',name, age, hundred)


name = input('What is your name? \n')
age = int(input('How old are you? \n'))
hundread_cal(name,age)

What is your name? 
Ranjith
How old are you? 
27
hello  Ranjith now u r in  27 You will turn 100 years old in Ranjith 27 2095


### 2.	What is pandas groupby? Demonstrate with your own example

In [8]:
import pandas as pd

a = {'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings','kings', 'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'],
     'Rank': [1, 2, 2, 3, 3,4 ,1 ,1,2 , 4,1,2]}


In [14]:
df = pd.DataFrame(a)
group_by=df.groupby(['Team','Rank']).groups
group_by

{('Devils', 2): [2], ('Devils', 3): [3], ('Kings', 1): [6, 7], ('Kings', 3): [4], ('Riders', 1): [0], ('Riders', 2): [1, 8, 11], ('Royals', 1): [10], ('Royals', 4): [9], ('kings', 4): [5]}

### 3.	How to create a dataframe from list?

In [17]:
import pandas as pd
names = ['Katie', 'Nik', 'James', 'Evan'] ## LIST 
df = pd.DataFrame(names, columns=['Name']) ## Converting list to Data fraome
df

Name
0  Katie
1    Nik
2  James
3   Evan

### 4.	What are the ways to combine the dataframe in pandas. Give an example for each

In [20]:
# 1.Concatenating
# 2.Joining DataFrames 
import pandas as pd
# First DataFrame
df1 = pd.DataFrame({'id': ['A1', 'A2', 'A3', 'A4'],
                    'Name': ['Ranjith', 'Shuan', 'Karthik', 'Narayan']})
  
# Second DataFrame
df2 = pd.DataFrame({'id': ['B1', 'B2', 'B3', 'B4'],
                    'Name': ['Chennai', 'Mumbai', 'Kerala', 'pune']})



[   id     Name
0  A1  Ranjith
1  A2    Shuan
2  A3  Karthik
3  A4  Narayan,    id     Name
0  B1  Chennai
1  B2   Mumbai
2  B3   Kerala
3  B4     pune]


id     Name
0  A1  Ranjith
1  A2    Shuan
2  A3  Karthik
3  A4  Narayan
0  B1  Chennai
1  B2   Mumbai
2  B3   Kerala
3  B4     pune

In [24]:
#1. concate
##print(frames)
result = pd.concat([df1, df2])
result

id     Name
0  A1  Ranjith
1  A2    Shuan
2  A3  Karthik
3  A4  Narayan
0  B1  Chennai
1  B2   Mumbai
2  B3   Kerala
3  B4     pune

In [26]:
# Joinner
result = pd.concat([df1, df2], axis=0, join='inner')
display(result)

id     Name
0  A1  Ranjith
1  A2    Shuan
2  A3  Karthik
3  A4  Narayan
0  B1  Chennai
1  B2   Mumbai
2  B3   Kerala
3  B4     pune

### 5.	What is the difference between list and tuples in Python? 

In [31]:
##LIST
## List is a container to contain different types of objects and is used to iterate objects
## SYNTAX is [] or object list()
## we can use to data manupuaion with i list
L=[1,2,3,'Ranjith','shaun']
## we can able to re modify value content has mutabble
L[0]='test'
L

['test', 2, 3, 'Ranjith', 'shaun']

In [30]:
##tuples
## tuples is a container to contain different types of objects and is used to iterate objects
## SYNTAX is () or object tuple()
## we can't use to data manupuaion with in tuples only readble
tup = ('a', 'b', 'c', 'd', 'e')
## we can'n able to re modify value content has immutabble
tup[0] = 2 ## show immutable error

tup

TypeError: 'tuple' object does not support item assignment

### 6.	Find out the mean, median and standard deviation of this numpy array -> np.array([1,5,3,100,4,48])

In [32]:
import numpy as np

In [34]:
n1=np.array([10,20,30,40,50,60])
mean=np.mean(n1)
med=np.median(n1)
std=np.std(n1)
print(mean,med,std)

35.0 35.0 17.07825127659933


### 7.	How will you remove duplicate elements from a list

In [38]:
l=[1,1,1,2,2,3,3,4,5]
a=set(l)## convert from list to set also list should not support duplicate so its autmatically removed
l=list(a)## convert set to list
l

[1, 2, 3, 4, 5]

### 8.	What is a map() function in Python? Give an example

In [42]:
# map() function returns a map object(which is an iterator) of the results 
# after applying the given function to each item of a given iterable (list, tuple etc.)
def addition(n):
    return n + n

numbers = (1, 2, 3, 4)
result = map(addition, numbers)
print(list(result))

[2, 4, 6, 8]


### 9.	What is pass in Python?

In [43]:
# The pass statement is used as a placeholder for future code.
# When the pass statement is executed, nothing happens, but you avoid getting an error when empty code is not allowed
# Empty code is not allowed in loops, function definitions, class definitions, or in if statements
a = 33
b = 200
if b > a:
  pass

### 10.	What is vstack() in numpy? Give an example

In [46]:
# numpy.vstack() function is used to stack the sequence of input arrays vertically to make a single array.
import numpy as np

a1 = np.array([[ 1, 2, 3], [ -1, -2, -3]] )
#print ("1st Input array : \n", a1) 
  
a2 = np.array([[ 4, 5, 6], [ -4, -5, -6]] )
#print ("2nd Input array : \n", a2) 
  
# Stacking the two arrays vertically
out_arr = np.vstack((a1, a2))
out_arr

1st Input array : 
 [[ 1  2  3]
 [-1 -2 -3]]
2nd Input array : 
 [[ 4  5  6]
 [-4 -5 -6]]


array([[ 1,  2,  3],
       [-1, -2, -3],
       [ 4,  5,  6],
       [-4, -5, -6]])